package com.jobseekercopilot.documentstore.dto;

import com.jobseekercopilot.documentstore.entity.FileType;
import com.jobseekercopilot.documentstore.entity.FileSource;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Metadata for an exported document file")
public class DocumentFileResponse {

    @Schema(description = "Unique exported file ID", example = "550e8400-e29b-41d4-a716-446655440000")
    private UUID id;

    @Schema(description = "Generated document ID this file belongs to", example = "550e8400-e29b-41d4-a716-446655440000")
    private UUID generatedDocumentId;

    @Schema(description = "Exported file type", example = "DOCX", allowableValues = {"DOCX", "PDF"})
    private FileType fileType;

    @Schema(description = "Download filename", example = "cv.docx")
    private String fileName;

    @Schema(description = "File MIME type", example = "application/pdf")
    private String mimeType;

    @Schema(description = "Whether the file was generated by the system or uploaded by the user", example = "USER_UPLOADED")
    private FileSource source;

    @Schema(description = "Whether this is the active file for its document and type", example = "true")
    private boolean active;

    @Schema(description = "Monotonic version within this generated document and file type", example = "2")
    private int version;

    @Schema(description = "Object size in bytes", example = "18432")
    private long contentSize;

    @Schema(description = "Lowercase SHA-256 digest used to verify object integrity")
    private String contentSha256;

    @Schema(description = "Storage lifecycle status", example = "AVAILABLE")
    private com.jobseekercopilot.documentstore.entity.ObjectStorageStatus storageStatus;

    @Schema(description = "Timestamp when the object store accepted the file")
    private LocalDateTime storedAt;

    @Schema(description = "Timestamp when the exported file was saved")
    private LocalDateTime createdAt;

    @Schema(description = "Timestamp when the exported file was last updated")
    private LocalDateTime updatedAt;
}
